name: Deploy with MkDocs
on:
  push:
    branches: [ "mkdocs" ]

## Very important
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: MkDocs Deploy
        uses: yodamad-actions/mkdocs@0.1.0
