name: Slidesk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build presentation
        uses: docker://gouz/slidesk:latest
        with: 
          args: slidesk -s output slidesk

      - name: Verify output directory exists and is not empty
        shell: bash
        run: |
          set -euo pipefail
          ls -R          
          test -d "output"
          test -n "$(ls -A "output")" || { echo "Output dir is empty"; exit 1; }

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
